<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-60U4M33" failures="4" tests="14" name="Surefire test" time="74.318" errors="0" timestamp="2023-12-16T19:59:31 IST">
  <testcase classname="org.seleniumjavaautomation.junit.Junittest1" name="testMethodClass1 on testMethodClass1(org.seleniumjavaautomation.junit.Junittest1)" time="12.747"/>
  <testcase classname="org.seleniumjavaautomation.junit.Junittest2" name="testMethod1 on testMethod1(org.seleniumjavaautomation.junit.Junittest2)" time="22.794"/>
  <testcase classname="org.seleniumjavaautomation.junit.Junittest2" name="testMethod2 on testMethod2(org.seleniumjavaautomation.junit.Junittest2)" time="31.983"/>
  <testcase classname="org.seleniumjavaautomation.junit.Junittest2" name="testMethod3 on testMethod3(org.seleniumjavaautomation.junit.Junittest2)" time="37.755"/>
  <testcase classname="org.seleniumjavaautomation.junit.Junittest2" name="testMethod4 on testMethod4(org.seleniumjavaautomation.junit.Junittest2)" time="0.0">
    <skipped/>
  </testcase> <!-- testMethod4 on testMethod4(org.seleniumjavaautomation.junit.Junittest2) -->
  <testcase classname="org.seleniumjavaautomation.junit.JunitBCAC" name="testMethod1 on testMethod1(org.seleniumjavaautomation.junit.JunitBCAC)" time="45.552"/>
  <testcase classname="org.seleniumjavaautomation.junit.JunitBCAC" name="testMethod2 on testMethod2(org.seleniumjavaautomation.junit.JunitBCAC)" time="47.73"/>
  <testcase classname="org.seleniumjavaautomation.junit.JunitBCAC" name="testMethod3 on testMethod3(org.seleniumjavaautomation.junit.JunitBCAC)" time="47.886"/>
  <testcase classname="org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest" name="testJunitTimeoutException on testJunitTimeoutException(org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest)" time="53.96">
    <failure type="java.lang.Exception" message="test timed out after 2000 milliseconds">
      <![CDATA[java.lang.Exception: test timed out after 2000 milliseconds
at java.base@17.0.6/java.lang.Thread.sleep(Native Method)
at app//org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest.testJunitTimeoutException(JunitTimeoutAndEcpectedExceptionTest.java:44)
at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at app//org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
... Removed 4 stack frames]]>
    </failure>
  </testcase> <!-- testJunitTimeoutException on testJunitTimeoutException(org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest) -->
  <testcase classname="org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest" name="exceptiontest1 on exceptiontest1(org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest)" time="57.57">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest.exceptiontest1(JunitTimeoutAndEcpectedExceptionTest.java:52)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runners.Suite.runChild(Suite.java:127)
at org.junit.runners.Suite.runChild(Suite.java:26)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- exceptiontest1 on exceptiontest1(org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest) -->
  <testcase classname="org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest" name="exceptiontest2 on exceptiontest2(org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest)" time="61.272"/>
  <testcase classname="org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest" name="testJunitTimeoutException on testJunitTimeoutException(org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest)" time="5.583">
    <failure type="java.lang.Exception" message="test timed out after 2000 milliseconds">
      <![CDATA[java.lang.Exception: test timed out after 2000 milliseconds
at java.base@17.0.6/java.lang.Thread.sleep(Native Method)
at app//org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest.testJunitTimeoutException(JunitTimeoutAndEcpectedExceptionTest.java:44)
at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at app//org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
... Removed 4 stack frames]]>
    </failure>
  </testcase> <!-- testJunitTimeoutException on testJunitTimeoutException(org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest) -->
  <testcase classname="org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest" name="exceptiontest1 on exceptiontest1(org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest)" time="9.13">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest.exceptiontest1(JunitTimeoutAndEcpectedExceptionTest.java:52)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- exceptiontest1 on exceptiontest1(org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest) -->
  <testcase classname="org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest" name="exceptiontest2 on exceptiontest2(org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest)" time="12.826"/>
</testsuite> <!-- Surefire test -->
